name: thesis
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - pip
  - pdfminer==20191125=pyhd8ed1ab_1
  - pdfminer.six==20221105=pyhd8ed1ab_0
  - pip:
    - xgboost==1.7.2
    - torch==1.13.0
    - torchtext==0.14.0
    - sklearn==0.0.post1
    - pdfplumber==0.7.6
    - numpy==1.23.5
    - pandas==1.5.2
    - langdetect==1.0.9
    - transformers==4.24.0
    - scikit-learn==1.1.3
    - tqdm==4.64.1
    - nltk==3.7
    - gensim==4.2.0
    - ipykernel==6.19.2
    - matplotlib==3.6.2
    - srsly==2.4.5 
    - cymem==2.0.7
    - preshed==3.0.8
    - openpyxl==3.0.10 
    - smart-open==6.3.0 
    - catalogue==2.0.8 
    - confection==0.0.3 
    - cymem==2.0.7 
    - langcodes==3.3.0 
    - murmurhash==1.0.9 
    - pathy==0.10.1 
    - pydantic==1.10.2
    - beautifulsoup4==4.11.1
    - bs4==0.0.1 
    - soupsieve==2.3.2.post1
    - lxml==4.9.2
    # - spacy==3.4.3
    # - lis==0.7.9
    # - os==2.1.4

  